// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef CARMA_PLANNING_MSGS__MSG__INTERSECTION_TRANSIT_RIGHT_TURN_MANEUVER_HPP_
#define CARMA_PLANNING_MSGS__MSG__INTERSECTION_TRANSIT_RIGHT_TURN_MANEUVER_HPP_

#include "carma_planning_msgs/msg/detail/intersection_transit_right_turn_maneuver__struct.hpp"
#include "carma_planning_msgs/msg/detail/intersection_transit_right_turn_maneuver__builder.hpp"
#include "carma_planning_msgs/msg/detail/intersection_transit_right_turn_maneuver__traits.hpp"
#include "carma_planning_msgs/msg/detail/intersection_transit_right_turn_maneuver__type_support.hpp"

#endif  // CARMA_PLANNING_MSGS__MSG__INTERSECTION_TRANSIT_RIGHT_TURN_MANEUVER_HPP_
